export type TypeIcon = 'iconweixinzhifu-01' |
    'iconyuezhifu-01' |
    'iconkaohetongguo-01' |
    'iconkaohebutongguo-01' |
    'icondianhua-01' |
    'iconyoujian' |
    'iconweixin-01' |
    'iconQQ-01' |
    'iconxiugai-01' |
    'iconguanbi' |
    'iconyiwen' |
    'iconshuaxin' |
    'iconstatus-0' |
    'iconstatus-21' |
    'iconshouji' |
    'iconweixin' |
    'icondizhi' |
    'iconcha' |
    'iconfaoffer' |
    'iconbuheshi' |
    'iconruzhi' |
    'iconkaohe' |
    'iconyaomianshi' |
    'icongengduo' |
    'iconstatus' |
    'icongou' |
    'iconxiangqing' |
    'icondingwei1-01' |
    'iconlianxikefu' |
    'iconyonghushezhi' |
    'iconbangzhushouce' |
    'icondianhua' |
    'icondingwei' |
    'iconfenxiang' |
    'icongangweimoban' |
    'iconpaixu' |
    'iconqiyeguanli' |
    'iconqiehuan' |
    'iconshanchu' |
    'iconshangjin' |
    'iconsousuo' |
    'iconshoucang' |
    'iconwodeqianbao' |
    'iconxuanzhong' |
    'iconxiala' |
    'iconyishoucang' |
    ''
